---
env:
  node: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - "node_modules"
  - "dist"
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - error
    - windows
  # quotes:
  #   - error
  #   - double
  semi:
    - warn
    - always
